### ISSUE TITLE
Consider auto-unlock/lock

### ISSUE THREAD

**Issue by jeffbaumes** [OpenImaging/miqa#120]
Is there a way to auto acquire/release the lock on navigation to the experiment and session timeout?

**Comment by dzenanz** [comment]
Idea: when user accesses an experiment via task list, they automatically get exclusive edit right for all the experiments in the task list. When they navigate away from the experiment, if they have rated all the scans in the experiment, they should automatically release the exclusive lock they had on the experiment.

When a user views experiments from the project list, they should have to manually acquire the exclusive edit access. In this case, they should also manually release it.

In both cases, when they log out (either manually or due to idleness) they should release all the locks they had.

**Comment by annehaley** [comment]
Closing in favor of #173
