### ISSUE TITLE
Demo MIQA using Iowa PREDICT data and showcase to gather feeback

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#14]

**Comment by curtislisle** [comment]
big disk from UIowa is almost fully copied.  I have scripts to build a MIQA JSON from a scan list that I can run shortly and will try to injest using the new MIQA Version 2.

**Comment by curtislisle** [comment]
I am currently having trouble installing miqa-django.  I have received some help from Abhishek, but authentication is still broken.  It is probably because I don't understand how to correctly setup the OAuth process, the admin user, etc.  I will request tech assistance after we have Stanford up and going.

**Comment by curtislisle** [comment]
@dchiquito helped me get a working miqa-django on my linux system here at home using the all-docker development build!  We worked through some authentication issues.  I have successfully read a CSV and will test JSON import next.

**Comment by dzenanz** [comment]
I think this was done, we just forgot to close it. Reopen if you disagree.
