### ISSUE TITLE
Username/Password Not Working

### ISSUE THREAD

**Issue by davidshq** [OpenImaging/miqa#16]
I've used the instructions in the README.md to setup a docker instance. The instance seemed to install without issue and loaded the admin page at http://127.0.0.1/admin, however when I tried logging in I received a password incorrect notification:

> Please enter the correct username and password for a staff account. Note that both fields may be case-sensitive.

I thought this might be because I used the default username (root) and a well-known password (password) so I shut down the instance and ran the createsuperuser again:

`docker-compose run --rm django ./manage.py createsuperuser`

This time I used a new username and a complex password.

Attempting to login after running the instance again resulted in the same error message.

Note: I was warned when creating the original username/password that I was using a too common password but was allowed to manually bypass this verification.

~~I'm going to blow away the current instance and start from scratch and see if using a new username / complex password from the get go makes any difference.~~

I recreated the container, used a unique username and password, and attempted to login, still received the same error message.

**Comment by zachmullen** [comment]
Hi @davidshq ,

This is an idiosyncrasy with our out-of-the-box login settings, and the admin page makes it non-obvious: you have to log in with your email rather than your username.

Note that we could also change this policy and allow login via username. It's an easy switch if we want to go that route.

**Comment by davidshq** [comment]
Thanks @zachmullen, that works! Might be worth updating the readme to note in the meantime?

**Comment by zachmullen** [comment]
Great idea

**Comment by dzenanz** [comment]
> allow login via username

That would be logical.

**Comment by aashish24** [comment]
I agree, I ran into similar issue in the past. It would be great to allow both username and email to login or if one, update the UI as such. So is the decision is to support username only or both?

**Comment by brianhelba** [comment]
FYI, this bug is reported upstream as: https://github.com/girder/django-composed-configuration/issues/106

Note, Composed-Configuration has made the decision to force the username to be equivalent to a user's email address. If a downstream project wants to change this policy (thus allowing users to have a distinct username), that can be done. That's not necessarily a fix to the core problem, of course.

**Comment by aashish24** [comment]
thanks @brianhelba looks like that issue is still open. Are we waiting on someone to resolve it?

**Comment by brianhelba** [comment]
@aashish24 It's a hard bug to fix. If anyone wants to suggest a specific technical path forward in the upstream issue, I'd welcome it.

**Comment by brianhelba** [comment]
@zachmullen @aashish24 The upstream bug here is now fixes and released: https://github.com/girder/django-composed-configuration/releases/tag/v0.18.0

**Comment by aashish24** [comment]
fyi @dchiquito

**Comment by dchiquito** [comment]
I just verified that with a fresh `pip install`, the `python manage.py createsuperuser` no longer prompts twice for username/email, instead asking for one email and using it as the username. Since email is now consistently used for logins, I'm closing this.
