### ISSUE TITLE
Use MIQA UI for forgot password workflow

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#20]
Currently forgot password takes to you the Girder UI. We want to hide the implementation details and instead present MIQA specific UI to the user. 

Related to https://github.com/OpenImaging/miqa/issues/5

**Comment by dzenanz** [comment]
Did we fix this?

**Comment by dzenanz** [comment]
@annehaley did we fix this?

**Comment by annehaley** [comment]
It seems that our use of `django-allauth` includes this for us. The main login page has a "Forgot Password" button that brings you to this screen:
![image](https://user-images.githubusercontent.com/44912689/180254150-382c796f-9595-41e0-b8cf-1b651b6a62b6.png)
I tried it and successfully updated the password for a test account. 

Unless the goal of this issue was to do something custom to MIQA, we should keep this closed.
