### ISSUE TITLE
CSV with header but no entries results in breaking MIQA and showing unreadable error 

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#251]
This is related to Girder-3 version but might happen in Girder-4 as well

**Comment by annehaley** [comment]
To test this, I used an empty file `test1.csv` and a file `test2.csv` with the following contents:
```
project_name,experiment_name,scan_name,scan_type,frame_number,file_location

```
The current import function raises the following error when trying to perform these imports:
```
ValueError: Invalid format of import file
```
I expect that this is desired behavior. BUT, this is server-side printing only. The frontend does not propagate this error message to the user. I'll fix this so that the user will know what went wrong upon import.
