### ISSUE TITLE
Timeout dialog will continue counting in negatives

### ISSUE THREAD

**Issue by annehaley** [OpenImaging/miqa#371]
![image](https://user-images.githubusercontent.com/44912689/157763282-2adb4bc2-cd4b-44f1-8829-7187f768fb9a.png)

**Comment by dchiquito** [comment]
Do you have any steps to reproduce this? When I try it the page is logged out within a second of hitting `0:00`, as it should.

**Comment by annehaley** [comment]
Oddly, I am not able to reproduce anymore. The original error happened on the production instance twice in a row, but returning to the site today, it's doing a successful logout. Maybe this was a mishap? I'll keep an eye out if I can reproduce again, but for now I'll close this.

**Comment by zachmullen** [comment]
This happened to me yesterday, but I haven't made the effort to reproduce it yet. Here is what I did to trigger it:

1. Log in, go to a scan view page.
2. Go to a different tab so that the MIQA tab is not visible.
3. Wait some amount of time beyond the default timeout, then navigate back to the tab. The numbers were negative, and kept ticking down.

Browser: Chrome 99.0.4844.51

I noticed one other symptom here, which is the way the numbers are formatted. Rather than always padding the seconds, single-digit second values don't have a leading zero, e.g. `1:3` as opposed to the more expected `1:03`. It's also visible in the screenshot above.
