### ISSUE TITLE
Auto-evaluation not available for scans added via "Add scans"

### ISSUE THREAD

**Issue by dzenanz** [OpenImaging/miqa#403]
This happens on https://miqa.miqaweb.io/

**Comment by annehaley** [comment]
I'm not able to replicate the issue on my development instance (evaluations appear after 10 seconds). Perhaps this is a configuration issue on the deployed instance. miqaweb still does the polling correctly so we can assume the evaluation object is just not made. Sentry didn't raise any errors about the NN failing, but this may be because that happens in celery, not django. @zachmullen could we work together to diagnose this?

**Comment by zachmullen** [comment]
Fixed, just needed to update the worker. I need to grant others the ability to run the worker update ansible stuff.
