### ISSUE TITLE
If one just presses usable then the command field in the csv file does not record the date and user anymore

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#413]

**Comment by zachmullen** [comment]
This seems like a good next candidate for an end-to-end test

**Comment by aashish24** [comment]
I agree @zachmullen. @dchiquito what do you think?

**Comment by annehaley** [comment]
I'm not able to replicate the problem.
The CSV format does not encode the datetime of the decision at all (there is no column for that). In trying to replicate this, the user column is successfully filled for scans where I simply clicked "Usable" for a decision.

**Comment by annehaley** [comment]
After discussing with @zachmullen, it is possible that the Stanford deployment writes a blank value for the user because we explicitly write `user.username` to the file, whereas a User may only have `user.email` supplied (only email is necessary for login). 

I have put in https://github.com/OpenImaging/miqa/pull/417 to make the imports and exports use either username or email of the last decision's creator. This is my best guess at the problem, if the problem persists on the Stanford deployment after this change, we may need a more specific description of the problem.

As for persisting the datetime of the decision object through export-import cycles, this would be a new addition to the CSV format and we should discuss that as a team.

**Comment by annehaley** [comment]
Closed by #425
