### ISSUE TITLE
"samples/" data bloats the Git repository size

### ISSUE THREAD

**Issue by brianhelba** [OpenImaging/miqa#483]
After a fresh `git clone`, the size of the `.git/` directory in this repository is 104MB. Having larger repo sizes decreases accessibility to developers, particularly ones with poor internet connections.

It looks like this repo [is using Git-LFS](https://github.com/OpenImaging/miqa/commit/062e2154381ef8a7e587984c6807d7b20eaabf16), but it's only configured to match `*.pth` files. The [recently-added `samples/**/*.nii.gz` files](https://github.com/OpenImaging/miqa/commit/40fe8f80c6e20b0321423c9b6d5570f6188d94f5) were added as blobs to the Git tree itself, and consume 93MB.

---

To robustly resolve this issue, you'll need to rewrite the history of `master`, to remove direct blob references and put all content into Git-LFS. Here's a starting point for that process: https://docs.github.com/en/repositories/working-with-files/managing-large-files/moving-a-file-in-your-repository-to-git-large-file-storage

Alternatively, you could [easily configure](https://www.mankier.com/1/git-lfs-track) new files in `samples/**` (or some similar pattern) to go into Git-LFS, and accept that the old ones will forever be included in a fresh `git clone` (even if you delete them from the working tree in the future).

**Comment by annehaley** [comment]
I followed the tutorial provided and ran the following commands on the repository: `git lfs migrate import --everything --include="*.nii.gz"` followed by `git push origin --force --all`. @zachmullen pulled the new history on heroku, too. This slightly reduced the repo size, though it didn't completely erase the larger files from the history. We can consider this resolved for now because `.nii.gz` files will use git LFS in future commits; we can revisit this later if the repository size proves to be a problem.
