### ISSUE TITLE
Schema Inconsistency? 

### ISSUE THREAD

**Issue by davidshq** [OpenImaging/miqa#58]
In comparing the schema with girder miqa to the schema with django miqa I noticed  that in `data_import.py`:
1. `additional_properties` is changed to `additionalProperties`
2. `imagePattern` is changed to `image_pattern`

It seems that overall the naming convention is `some_name` (experiment_id, site_id, user_fields) rather than `someName`. Is there a reason for the aberration?

**Comment by zachmullen** [comment]
`additionalProperties` [is part of JSON-Schema itself](https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties), not part of our schema. I assume it was a bug in the old system; someone was trying to set `additionalProperties` and just used the wrong format.

As for your second one, that was an intentional change to bring things consistently into snake_case. Our assumption was that this JSON schema is internal-facing only, and so could be changed without disruption.

**Comment by davidshq** [comment]
Thanks Zach, I appreciate the clarification. Makes perfect sense.
