### ISSUE TITLE
After import, the project page does not update correctly

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#593]
Reported by @kipohl 
https://files.slack.com/files-pri/T0AGVLRKQ-F042L1UT7HR/image.png

**Comment by annehaley** [comment]
Actually I cannot replicate this; the project overviews update immediately for me, because we already invoke a refresh immediately after import:
![image](https://user-images.githubusercontent.com/44912689/190665147-d1fb5fb9-e769-4766-b9bd-b3ee1dbe2daf.png)
What is meant by "does not update correctly"? Is the update not happening or is the updated information wrong?

**Comment by annehaley** [comment]
@kipohl Can you provide clarification?

**Comment by kipohl** [comment]
it is not happening

**Comment by aashish24** [comment]
Related to #601
