### ISSUE TITLE
Some URLs cause web page to hang 

### ISSUE THREAD

**Issue by zachmullen** [OpenImaging/miqa#619]
Opening the following URL as a logged-in user (demo user or my real user both work to reproduce) causes the page to hang indefinitely: https://miqa.miqaweb.io/#/8de7d826-bd20-469c-b795-1dd7357d279d/8ac806fe-44cd-41f3-a438-a0fb4abcc929

This is on Chrome v106.0.5249.119 and MacOS 12.1 M1

Can anyone else reproduce?

**Comment by dzenanz** [comment]
This happens to me too. Win10, Chrome Version 106.0.5249.119 (Official Build) (64-bit).

**Comment by dzenanz** [comment]
It happens with both demo and my user.

**Comment by annehaley** [comment]
From testing this, I found that this only occurs when navigating to a complete scan from a fresh context (i.e. not navigating to the page from somewhere else in the app; refreshing the page at these urls or pasting them in results in the hanging behavior).

When the page is hanging in that state, it is waiting for a response from the `project_overview` endpoint. The request is properly invoked and structured, but it gets into a state where the "initial connection" step is not completed. 
![image](https://user-images.githubusercontent.com/44912689/197562518-dbced2e9-48bd-4b6d-9699-1620839ce784.png)

Opening the same request in a new tab gets a proper response (ruling out any server error happening for that request due to project state). Another interesting thing I found is that this state does not occur for the same urls when I apply throttling to the network. 

So far I have no suspect causes. Does anyone else recognize these symptoms?

**Comment by zachmullen** [comment]
Firefox dumped me here when I launched the debugger while it was hanging:

<img width="684" alt="Screen Shot 2022-10-28 at 10 17 00 AM" src="https://user-images.githubusercontent.com/555959/198651438-6e47106f-fe3f-4014-be9c-dcbde53151a7.png">

This is in `store/index.ts`

**Comment by zachmullen** [comment]
Fixed! Thanks @annehaley

**Comment by annehaley** [comment]
All thanks to you! And Firefox debug tools :)

Resolved by #627
