### ISSUE TITLE
OpenImaging organization needs a better icon.

### ISSUE THREAD

**Issue by hjmjohnson** [OpenImaging/miqa#7]

**Comment by jeffbaumes** [comment]
I replaced the placeholder logo with the MIQA logo. See https://github.com/OpenImaging

Designing another logo would be a larger effort and we can open a new issue if we feel it's needed. Since we have the landing page for MIQA and this is just for the GitHub org it may not be high priority to create a separate icon.

**Comment by aashish24** [comment]
thanks @jeffbaumes just wondering if the icon has transparent background? On my blach github theme it seems to have some pixels that is showing up in the background. Can we upload miqa icon with transparent background if that is available and not used already?

**Comment by jeffbaumes** [comment]
Dark mode shows up like this for me:

![image](https://user-images.githubusercontent.com/81305/125815879-d452ff3f-2cf3-4f6a-bdce-ef72ba6c6c0a.png)

I used the transparent-background SVG logo used on https://miqa.kitware.com. I think the white in there is intended as white in the SVG and is not supposed to be transparent.

**Comment by aashish24** [comment]
that is what I am seeing too, thanks for clarification, this is good for now, I was just wondering if the white / gray was not supposed to be seen. thanks.
